### ISSUE TITLE
`mlaunch list` throwing an exception on MacOS El Capitan 

### ISSUE THREAD

**Issue by lmeadows** [rueckstiess/mtools#387] opened 2015-12-16 21:21 UTC
When I run *mlaunch init --replicaset* I get the expected output:
> launching: mongod on port 27017
> launching: mongod on port 27018
> launching: mongod on port 27019

But when I then try to run *mlaunch list* I get the following exception:

```
$ mlaunch list
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools==1.1.9', 'console_scripts', 'mlaunch')()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 1337, in main
    tool.run()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 254, in run
    getattr(self, self.args['command'])()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 578, in list
    processes = self._get_processes()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 1134, in _get_processes
    if p.name() not in ['mongos', 'mongod']:
  File "/Library/Python/2.7/site-packages/psutil/__init__.py", line 539, in name
    cmdline = self.cmdline()
  File "/Library/Python/2.7/site-packages/psutil/__init__.py", line 592, in cmdline
    return self._proc.cmdline()
  File "/Library/Python/2.7/site-packages/psutil/_psosx.py", line 209, in wrapper
    raise ZombieProcess(self.pid, self._name, self._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=69)
```

Restarting the system did not fix the issue.

I'm running **MacOS El Capitan version 10.11.2 (15C50)**

**Comment by rueckstiess** [comment] 2016-01-20 02:50
Hi @lmeadows,

First of all, sorry for the delay...

I'm having trouble reproducing the issue on my end. I'm also using El Capitan and `mlaunch list` works without issues: 

<img width="908" alt="screen shot 2016-01-20 at 1 47 16 pm" src="https://cloud.githubusercontent.com/assets/99221/12438602/785edc10-bf7c-11e5-8442-f916df6a4438.png">

What version of psutil are you using? You can find out via
```bash
python -c "import psutil; print psutil.__version__"
3.2.1
```

**Comment by lmeadows** [comment] 2016-01-20 02:58
Hi @rueckstiess 
Running the command you gave me shows that I am using psutil version 3.3.0.

**Comment by rueckstiess** [comment] 2016-01-20 03:06
There seem to be similar reports on other projects with v3.3.0 and El Capitan, for example here: http://stackoverflow.com/questions/34081476/zombie-process-running-xlwings

Could you try downgrading your psutil package to 3.2.x and see if that works? You can do that like so:
```
pip uninstall psutil
pip install psutil==3.2.2
```

You may have to add `sudo` before the `pip` commands depending on your environment.

**Comment by rueckstiess** [comment] 2016-01-20 03:08
I'll have a look at your pull request meanwhile so we can fix it for the next version.

**Comment by rueckstiess** [comment] 2016-01-20 03:22
Okay just confirmed when I upgrade to psutil 3.3.x or higher, it breaks due to the Zombie processes, but with your fix it works again. I've merged it into the develop branch and it will be included in the next version of mtools. In the mean time, the workaround is to downgrade to psutil 3.2.2 as above.

Thanks for your contribution, much appreciated!

**Closed** 2016-01-20 03:24 UTC
Labels: bug

**Comment by lmeadows** [comment] 2016-01-20 03:27
Hi @rueckstiess 

I did the psutil downgrade you suggested, and found that it fixed the `mlaunch list` command.
