### ISSUE TITLE
UnicodeEncodeError in mlogfilter line 111 

### ISSUE THREAD

**Issue by interannette** [rueckstiess/mtools#643] opened 2018-07-02 17:20 UTC
Using 1.5.0, I am seeing a UnicodeEncodeError when running mlogfilter on a log file containing queries with ™
 
### Expected behavior
I am running "mlogfilter file1.log file2.log --markers none > combined.log" where file1.log contains a query with ™. I expect the combined.log file will contain all the lines from file1.log and file2.log

### Actual/current behavior
An error is displayed in the command line:

> Traceback (most recent call last):
>   File "/usr/local/bin/mlogfilter", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 355, in main
>     tool.run()
>   File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 343, in run
>     self.args['human'])
>   File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 111, in _outputLine
>     print(line)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 865: ordinal not in range(128)
> 

And the combined.log file only contains lines before the line with the special character.

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.5.0 |
| MongoDB server   | log files from 3.2.16
| Operating system | OSX 10.12.6 
| Python | 2.7.15

**Comment by interannette** [comment] 2018-07-02 17:22
Some googling led me to change line 111 of mlogfilter.py
from print(line) to print(line.encode('utf-8'))

That works for me, but I don't know enough about this project/python to know if there is a more comprehensive fix needed.

**Comment by stennie** [comment] 2018-07-02 21:30
@interannette Can you provide an example log line so we can write a test case?

Thanks,
Stennie

**Comment by interannette** [comment] 2018-07-02 21:42
@stennie here's a line that breaks it:

> 2018-07-02T00:01:01.123+0000 I COMMAND [conn1] command MyDB.MyCollection command: insert { insert: "MyCollection", ordered: true, writeConcern: { w: 2 }, documents: [ { _id: ObjectId('507f191e810c19729de860ea'), "myField":"String with ™"} ninserted:1 keyUpdates:0 writeConflicts:0 numYields:0 reslen:80 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, Database: { acquireCount: { w: 2 } }, Collection: { acquireCount: { w: 1 } }, Metadata: { acquireCount: { w: 1 } }, oplog: { acquireCount: { w: 1 } } } protocol:op_query 1052ms

it gets me the same error message as in my original post but with a different position.

**Comment by stennie** [comment] 2018-07-04 09:22
@interannette I can't reproduce this problem with your log line above and the same versions of `mlogfilter` & Python on macOS. Can you still reproduce the problem if you copy the log line from your earlier comment here?

If so, can you share the output of `python -m locale`? I'm wondering if perhaps your default locale is not set to UTF-8.

You could also confirm this theory by explicitly setting a UTF8 default, eg:

`LC_ALL="en_US.UTF-8" mlogfilter ...` 

Thanks,
Stennie

**Comment by interannette** [comment] 2018-07-05 14:31
@stennie, I copied the line from above and pasted it into a text file, test.log and ran it from the command line like so (result included):

`mlogfilter test.log > test.txt`
> Traceback (most recent call last):
>   File "/usr/local/bin/mlogfilter", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 355, in main
>     tool.run()
>   File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 343, in run
>     self.args['human'])
>   File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 111, in _outputLine
>     print(line)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 235: ordinal not in range(128)

My output from python -m locale is: 

> Locale aliasing:
> 
> Locale defaults as determined by getdefaultlocale():
> ------------------------------------------------------------------------
> Language:  en_US
> Encoding:  UTF-8
> 
> Locale settings on startup:
> ------------------------------------------------------------------------
> LC_NUMERIC ...
>    Language:  (undefined)
>    Encoding:  (undefined)
> 
> LC_MESSAGES ...
>    Language:  (undefined)
>    Encoding:  (undefined)
> 
> LC_MONETARY ...
>    Language:  (undefined)
>    Encoding:  (undefined)
> 
> LC_COLLATE ...
>    Language:  (undefined)
>    Encoding:  (undefined)
> 
> LC_CTYPE ...
>    Language:  (undefined)
>    Encoding:  (undefined)
> 
> LC_TIME ...
>    Language:  (undefined)
>    Encoding:  (undefined)
> 
> 
> Locale settings after calling resetlocale():
> ------------------------------------------------------------------------
> LC_NUMERIC ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_MESSAGES ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_MONETARY ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_COLLATE ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_CTYPE ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_TIME ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> 
> Locale settings after calling setlocale(LC_ALL, ""):
> ------------------------------------------------------------------------
> LC_NUMERIC ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_MESSAGES ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_MONETARY ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_COLLATE ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_CTYPE ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> LC_TIME ...
>    Language:  en_US
>    Encoding:  UTF-8
> 
> 
> Number formatting:
> 
> 123,456,789 is 123456789
> 3.14 is 3.14

I'm not sure if this is what you meant with the last suggestion, but I ran this from the command line: `LC_ALL="en_US.UTF-8" mlogfilter test.log > test.txt` and got the same error as before. If that's now how you meant for me to run it, let me know and I can retest.

**Comment by stennie** [comment] 2018-07-09 02:48
This will be fixed in the 1.5.2 release by way of PR #651 (Thanks @kevinadi!)

**Closed by stennie** 2018-07-09 02:48 UTC
Labels: bug, util/other

**Comment by interannette** [comment] 2018-07-10 00:15
Thanks for the update and quick fix @kevinadi !

**Comment by abdelhady** [comment] 2018-11-05 13:14
I've built mtools from the latest on develop, & even added the python environment variable `PYTHONIOENCODING=utf-8`, 
but I'm still getting the same error when redirecting the output from `mlogfilter` to `mlogvis`
