### ISSUE TITLE
hope support mongodb 4.4+ json log format

### ISSUE THREAD

**Issue by ikool-cn** [rueckstiess/mtools#881] opened 2022-07-12 06:12 UTC
When i am try use this tool, an error occurred:
Error: </data/mongodb/log/primary.log> does not appear to be a supported MongoDB log file format

**Comment by xiaoyunjie** [comment] 2022-09-08 09:49
I hope so too

**Comment by hyeonghwa** [comment] 2022-09-27 11:27
me too.

**Comment by stennie** [comment] 2022-10-03 06:31
Dupe of #806.

**Closed by stennie** 2022-10-03 06:31 UTC
Labels: duplicate, improvement
