### ISSUE TITLE
mplotqueries figure window not show in ubuntu 14

### ISSUE THREAD

**Issue by jiucai** [rueckstiess/mtools#385] opened 2015-11-17 07:22 UTC
mplotqueries figure windows not show in ubuntu 14

I'm using ubuntu 14,
>  uname -a
```
Linux vm-u14 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I installed mtools and its dependencies

> python -c "import pymongo; print pymongo.version"

```
3.1
```

>python -c "import matplotlib; print matplotlib.\__version\__"

```
1.5.0
```

> mplotqueries --version

```
mtools version 1.1.9
```
I am using Python 2.7.10, 
and installed 
> sudo apt-get install libpng-dev libjpeg8-dev libfreetype6-dev 
> pip install matplotlib

When mplotqueries executed finished, not figure  window displays,
It works in my Windows 7, but not works in Ubuntu ,
### Is there something wrong ? Please help.

> mplotqueries filter.log  --type histogram --bucketsize 1

```                                                                                    
HISTOGRAM plot
   id   #points  group
    1      4227  grilled.indigo.papaya

keyboard shortcuts (focus must be on figure window):

           p  switch to pan mode
           o  switch to zoom mode
    left/right  back / forward
           h  home (original view)
           l  toggle log/linear y-axis
           f  toggle fullscreen
         1-9  toggle visibility of top 10 individual plots 1-9
           0  toggle visibility of all plots
           -  toggle visibility of legend
           g  toggle grid
           c  toggle 'created with' footnote
           s  save figure
           q  quit mplotqueries
```

**Comment by jimoleary** [comment] 2015-11-17 10:11
I suspect the issue is due to the backend that is being used by matplotlib.

I had to build matplotlib from source, install python-tk and change the backend to be TkAgg.

On Ubuntu 15.10, the following worked for me:

    sudo apt-get install build-essential python-dev tk-dev libpng-dev libffi-dev dvipng texlive-latex-base python-tk
    pip uninstall matplotlib
    git clone git@github.com:matplotlib/matplotlib.git
    cd matplotlib
    git checkout v1.5.0
    python setup.py build
    python setup.py install
    pip list 
    mkdir -p ~/.config/matplotlib
    echo "backend : TkAgg"  >>  ~/.config/matplotlib/matplotlibrc
    python -c "from matplotlib import pyplot as plt; plt.plot([1, 1]); plt.show()"


If the final command shows a pop up window then it is likely that a non-gui backend was the issue. Try your mplotqueries command again.

**Comment by jiucai** [comment] 2015-11-18 05:15
I do all the commands you provided
> pip list 

```
cycler (0.9.0)
distribute (0.7.3)
matplotlib (1.5.0)
mtools (1.1.9)
numpy (1.10.1)
pip (7.1.2)
psutil (3.2.2)
pymongo (3.1)
pyparsing (2.0.6)
python-dateutil (2.2)
pytz (2015.7)
setuptools (15.2)
six (1.10.0)

```

 but when execute your last test case, python show me errors:
*** How could to resolve it , thanks.

> python -c "from matplotlib import pyplot as plt; plt.plot([1, 1]); plt.show()"

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/lib/pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib-1.5.0-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/data/lib/pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib-1.5.0-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/data/lib/pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib-1.5.0-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/data/lib/pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib-1.5.0-py2.7-linux-x86_64.egg/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/data/lib/pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib-1.5.0-py2.7-linux-x86_64.egg/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/data/lib/pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib-1.5.0-py2.7-linux-x86_64.egg/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/data/lib/pyenv/versions/2.7.10/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter

```

**Comment by stennie** [comment] 2016-07-17 13:28
@jiucai This issue was created a while ago so I'm assuming you've found a solution (perhaps using `mplotvis`, which does not require matplotlib). I'm going to close the issue, but it might help others if you comment here with your solution.

Regards,
Stennie

**Closed by stennie** 2016-07-17 13:28 UTC
Labels: mplotqueries

**Comment by iljapelech** [comment] 2016-07-20 07:53
That @jimoleary's config file made it working on my openSuse (42.1) box. 
I think this check shoul be put into install documentation.
