### ISSUE TITLE
Fails with Type Error TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by gopisera** [rueckstiess/mtools#569] opened 2018-01-05 18:34 UTC
### Actual/current behavior

Error:

Initated command : mlaunch init --sharded 3 --replicaset  --nodes 2 --config 3 --auth
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
launching: mongod on port 27021
launching: mongod on port 27022
launching: mongod on port 27023
launching: config server on port 27024
launching: config server on port 27025
launching: config server on port 27026
replica set 'configRepl' initialized.
replica set 'shard01' initialized.
replica set 'shard02' initialized.
replica set 'shard03' initialized.
launching: mongos on port 27017
adding shards. can take up to 30 seconds...
Traceback (most recent call last):
  File "/usr/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools==1.3.3.dev0', 'console_scripts', 'mlaunch')()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 2011, in main
    tool.run()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 529, in run
    getattr(self, self.args['command'])()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 757, in init
    self.restart()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 1057, in restart
    processes = self._get_processes()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 1679, in _get_processes
    name = p.name()
TypeError: 'str' object is not callable
mongo@cdllbosdbc001s2:/app/mysql/mongo/mtools-develop/data> python
Python 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
  

### Environment

| Software         | Version
| ---------------- | -------
| mtools           |   1.3.3-dev
| MongoDB server   |  3.6
| Operating system |  SUSE 

Error:

Initated command : mlaunch init --sharded 3 --replicaset  --nodes 2 --config 3 --auth
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
launching: mongod on port 27021
launching: mongod on port 27022
launching: mongod on port 27023
launching: config server on port 27024
launching: config server on port 27025
launching: config server on port 27026
replica set 'configRepl' initialized.
replica set 'shard01' initialized.
replica set 'shard02' initialized.
replica set 'shard03' initialized.
launching: mongos on port 27017
adding shards. can take up to 30 seconds...
Traceback (most recent call last):
  File "/usr/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools==1.3.3.dev0', 'console_scripts', 'mlaunch')()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 2011, in main
    tool.run()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 529, in run
    getattr(self, self.args['command'])()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 757, in init
    self.restart()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 1057, in restart
    processes = self._get_processes()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 1679, in _get_processes
    name = p.name()
TypeError: 'str' object is not callable
mongo@cdllbosdbc001s2:/app/mysql/mongo/mtools-develop/data> python
Python 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

**Comment by gopisera** [comment] 2018-01-05 18:34
Error:

Initated command : mlaunch init --sharded 3 --replicaset  --nodes 2 --config 3 --auth
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
launching: mongod on port 27021
launching: mongod on port 27022
launching: mongod on port 27023
launching: config server on port 27024
launching: config server on port 27025
launching: config server on port 27026
replica set 'configRepl' initialized.
replica set 'shard01' initialized.
replica set 'shard02' initialized.
replica set 'shard03' initialized.
launching: mongos on port 27017
adding shards. can take up to 30 seconds...
Traceback (most recent call last):
  File "/usr/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools==1.3.3.dev0', 'console_scripts', 'mlaunch')()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 2011, in main
    tool.run()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 529, in run
    getattr(self, self.args['command'])()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 757, in init
    self.restart()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 1057, in restart
    processes = self._get_processes()
  File "/usr/lib/python2.7/site-packages/mtools-1.3.3.dev0-py2.7.egg/mtools/mlaunch/mlaunch.py", line 1679, in _get_processes
    name = p.name()
TypeError: 'str' object is not callable
mongo@cdllbosdbc001s2:/app/mysql/mongo/mtools-develop/data> python
Python 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

**Comment by stennie** [comment] 2018-04-30 01:33
Looks like a duplicate of #572. This should be fixed by updating to a newer version of `psutil`. We've tested `psutil` >=5.4.2 with the upcoming release of mtools 1.4.0.

If you are still encountering this issue in mtools >= 1.4.0 please open a new bug report.

Thanks,
Stennie

**Closed by stennie** 2018-04-30 01:33 UTC
Labels: mlaunch, question
