### ISSUE TITLE
mloginfo --distinct --verbose gives 'TypeError :' cannot concatenate 'str' and 'LogEvent' objects

### ISSUE THREAD

**Issue by Jagman13** [rueckstiess/mtools#729] opened 2019-08-21 16:07 UTC
### Actual/current behavior
 mloginfo mongod.log --verbose --distinct
     source: mongod.log
       host: unknown
      start: 2019 Aug 13 01:00:01.335
        end: 2019 Aug 13 06:50:01.886
date format: iso8601-utc
     length: 6792
     binary: unknown
    version: = 2.6.x (iso8601 format)
    storage: unknown

DISTINCT
Traceback (most recent call last):
  File "/usr/bin/mloginfo", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/mtools/mloginfo/mloginfo.py", line 95, in main
    tool.run()
  File "/usr/lib/python2.7/site-packages/mtools/mloginfo/mloginfo.py", line 90, in run
    section.run()
  File "/usr/lib/python2.7/site-packages/mtools/mloginfo/sections/distinct_section.py", line 92, in run
    print("couldn't match:" + logevent)
TypeError: cannot concatenate 'str' and 'LogEvent' objects

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.5.3
| MongoDB server   | v4.0.12
| Operating system | centos-release-7-6.1810.2.el7

**Comment by stennie** [comment] 2019-09-07 02:10
@Jagman13 Can you provide a log snippet that demonstrates this error?

Thanks,
Stennie

**Comment by p-mongo** [comment] 2019-09-07 07:17
L degradeI 3 see you at the end we're rrt see see to tt45tr4 tree seesee see see see d Dr4
null

**Comment by stennie** [comment] 2019-12-28 18:04
Closing due to lack of details to reproduce this issue. Also, Python 2.7 is no longer supported.

If this issue is still reproducible with the latest version of mtools please open a new issue with a log snippet that demonstrates the error.

Thanks,
Stennie

**Closed by stennie** 2019-12-28 18:04 UTC
Labels: bug, mloginfo
