### ISSUE TITLE
Documentation for running mtools in Python script

### ISSUE THREAD

**Issue by allanx2000** [rueckstiess/mtools#482] opened 2017-04-26 13:48 UTC
I am trying to run the tools from my own script but looking at the code, can't figure out how to do it. I've tried using subprocess.call but it just returns the Usage lines.

`subprocess.call(["mlogfilter", "--json", "--logfile \"" + f + "\""])`
mlogfilter: error: unrecognized arguments: --logfile "C:\Users\xx63439\Desktop\My Folder\Logs Analysis\20170425\mongod.log.2017-04-21T03-59-01"

`subprocess.call(["mlogfilter", "\"" + f + "\"", "--json"])`
mlogfilter: error: unrecognized arguments: "C:\Users\xx63439\Desktop\My Folder\Logs Analysis\20170425\mongod.log.2017-04-21T03-59-01"

**Comment by stennie** [comment] 2017-09-14 12:42
@allanx2000 Apologies no one replied to your question earlier; this issue is a duplicate of #404.

The scripts are currently intended to be used via an interactive terminal and there are some assumptions that break non-TTY usage. The changes appear to be trickier than a simple tweak and we haven't had any volunteers to work out what is required. A PR would be appreciated if you are motivated to fix (or already have :).

Thanks,
Stennie

**Closed by stennie** 2017-09-14 12:42 UTC
Labels: help wanted, mlogfilter, question
