### ISSUE TITLE
"unknown string format" error while parsing logfile with unexpected line breaks

### ISSUE THREAD

**Issue by viralpuja** [rueckstiess/mtools#443] opened 2016-09-02 13:01 UTC
Virals-MacBook-Pro:rs1 vshah$ mloginfo 1.log log --connections
     source: 1.log
       host: Virals-MacBook-Pro.local:27017
      start: 2016 Feb 21 15:34:41.375
        end: 2016 Apr 12 13:06:48.932
date format: iso8601-local
     length: 749089
     binary: mongod
    version: 3.0.8
    storage: mmapv1

CONNECTIONS
Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/mtools/mloginfo/mloginfo.py", line 83, in main
    tool.run()
  File "/Library/Python/2.7/site-packages/mtools/mloginfo/mloginfo.py", line 78, in run
    section.run()
  File "/Library/Python/2.7/site-packages/mtools/mloginfo/sections/connection_section.py", line 42, in run
    for logevent in self.mloginfo.logfile:
  File "/Library/Python/2.7/site-packages/mtools/util/logfile.py", line 208, in **iter**
    le = self.next()
  File "/Library/Python/2.7/site-packages/mtools/util/logfile.py", line 195, in next
    elif le.datetime:
  File "/Library/Python/2.7/site-packages/mtools/util/logevent.py", line 193, in datetime
    dt = self._match_datetime_pattern(split_tokens[offs:offs+4])
  File "/Library/Python/2.7/site-packages/mtools/util/logevent.py", line 293, in _match_datetime_pattern
    dt = dateutil.parser.parse(' '.join(tokens[:4]), default=datetime(year, 1, 1))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py", line 697, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py", line 303, in parse
    raise ValueError, "unknown string format"
ValueError: unknown string format

**Comment by rueckstiess** [comment] 2016-09-02 13:03
Are you able to share that log file?

**Comment by viralpuja** [comment] 2016-09-02 15:58
[1.log.zip](https://github.com/rueckstiess/mtools/files/452436/1.log.zip)

Compressed log file uploaded.

**Comment by rueckstiess** [comment] 2016-09-03 00:59
Hi @viralpuja 

Thanks, that was helpful. The issue with this log file is that the data contains unescaped line breaks  and thus contains many lines that are not in the right log line format. Here is an example:

```
2016-02-21T15:38:09.005-0500 D STORAGE  [conn4] MmapV1ExtentManager::allocateExtent desiredSize:8192 fromFreeList: 0 eloc: 0:7000
2016-02-21T15:38:09.006-0500 D STORAGE  [conn4] allocating new extent
2016-02-21T15:38:09.006-0500 D STORAGE  [conn4] MmapV1ExtentManager::allocateExtent desiredSize:131072 fromFreeList: 0 eloc: 0:9000
2016-02-21T15:38:09.008-0500 D STORAGE  [conn4] enron.messages: clearing plan cache - collection info cache reset
2016-02-21T15:38:09.009-0500 I WRITE    [conn4] insert enron.messages query: { _id: ObjectId('4f16fc97d1e2d32371003f04'), body: "
AUSTIN AT THE CAPITOL
701 EAST 11TH STREET
AUSTIN, TX  78701
tel: 512-478-1111
fax: 512-478-3700

Hotel Information: http://marriotthotels.com/AUSDT
...", filename: "3.", headers: { Content-Transfer-Encoding: "7bit", Content-Type: "text/plain; charset=us-ascii", Date: new Date(996522306000), From: "reservations@marriott.com", Message-ID: "<9573108.1075840323920.JavaMail.evans@thyme>", Mime-Version: "1.0", Subject: "83929275 Marriott  Reservation Confirmation Number", To: [ "ebass@enron.com" ], X-FileName: "eric bass 6-25-02.PST", X-Folder: "\ExMerge - Bass, Eric\Personal", X-From: "Reservations@Marriott.com", X-Origin: "BASS-E", X-To: "EBASS@ENRON.COM", X-bcc: "", X-cc: "" }, mailbox: "bass-e", subFolder: "personal" } ninserted:1 keyUpdates:0 writeConflicts:0 numYields:0 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, MMAPV1Journal: { acquireCount: { w: 8 } }, Database: { acquireCount: { w: 1, W: 1 } }, Collection: { acquireCount: { W: 1 } }, Metadata: { acquireCount: { W: 4 } } } 76ms
2016-02-21T15:38:09.009-0500 D STORAGE  [conn4] allocating new extent
2016-02-21T15:38:09.011-0500 D STORAGE  [conn4] MmapV1ExtentManager::allocateExtent desiredSize:65536 fromFreeList: 0 eloc: 0:29000
```

Nonetheless, I think the various scripts should be able to skip those lines without error and just ignore them. So this is indeed a bug that we want to fix. Thanks for reporting it!

**Comment by stennie** [comment] 2017-09-14 13:02
Related to #416

**Comment by stennie** [comment] 2019-06-13 14:40
Closing as a dupe of #416. Better support for multi-line log parsing would improve all log mtools since they use the same helper library.

**Closed by stennie** 2019-06-13 14:40 UTC
Labels: bug, mloginfo
